name:                hw-json-simd
version:             0.1.0.0
github:              "haskell-works/hw-json-simd"
license:             BSD3
author:              "John Ky"
maintainer:          "newhoggy@gmail.com"
copyright:           "2018 John Ky"

extra-source-files:
- cbits/simd.h
- cbits/simd.c
- cbits/simd-spliced.c
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/haskell-works/hw-json-simd#readme>

ghc-options: -Wall

dependencies:
- base >= 4.7 && < 5
- binary
- bits-extra
- bytestring
- hw-bits
- hw-prim
- lens
- parallel
- mmap
- prettyprinter
- split
- text
- vector
- word8

library:
  build-tools:
  - c2hs
  c-sources:
  - cbits/simd-spliced.c
  - cbits/simd.c
  include-dirs:
  - cbits
  source-dirs: src
  cc-options: -mssse3 -O3 -mlzcnt -mbmi2 -mavx2

executables:
  hw-json-simd-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hw-json-simd
    - optparse-applicative

tests:
  hw-json-simd-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hw-json-simd
